name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  provider: ^6.0.5
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  firebase_storage: ^12.4.7
  flutter_image_compress: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.0.0
  flutter_map: ^6.1.0
  latlong2: 0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3

# flutter_launcher_icons configuration should be placed outside the main pubspec.yaml structure.
# You can move it to the end of this file as shown below, or use a separate file (flutter_launcher_icons.yaml).

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

  - assets/images/icons/
  - assets/login_success.mp4
  - assets/images/others/
  - assets/images/buttons/
  - assets/images/logo/app_logo.jpg
  - assets/images/icons/welcome_screen/Logo.png
  - assets/images/icons/welcome_screen/subtitle.png
  - assets/images/icons/detail_home_screen/
  - assets/images/icons/menu_sidebar/
  - assets/images/icons/reward_icon/
  - assets/images/foods/appetizers/
  - assets/images/foods/ramen/
  - assets/images/foods/tempura/
  - assets/images/foods/party_set/
  - assets/images/foods/curry_sets/
  - assets/images/foods/maki_rolls/
  - assets/images/foods/nigiri/
  - assets/images/foods/gunkan/
  - assets/images/foods/drinks/
  - assets/images/foods/condiments/
  - assets/images/foods/moriawase_makimono_set/

  # - assets/images/foods/agemono/
  # - assets/images/foods/don/
  # - assets/images/foods/dressings/
  # - assets/images/foods/makimono/
  # - assets/images/foods/moriawaseMakimonoSet/
  # - assets/images/foods/noodles/
  # - assets/images/foods/partySet/
  # - assets/images/foods/sideDish/
  # - assets/images/foods/sushiBlack/
  # - assets/images/foods/sushiRed/
  # - assets/images/foods/sushiWhite/
  # - assets/images/foods/temaki/
  # - assets/images/foods/yakimono/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GaMaamli
      fonts:
        - asset: assets/fonts/GaMaamli.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-Extrabold.ttf
    - family: InknutAntiqua
      fonts:
        - asset: assets/fonts/welcome_screen/InknutAntiqua-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
        # see https://flutter.dev/to/font-from-package
  
  # flutter_icons configuration should be outside the flutter section.
